### ISSUE TITLE
New moon time is wrong

### ISSUE THREAD

**Issue by dannylin108** [jasonsturges/lunarphase-js#28]
Since the lib doesn't have a method to directly calculate new moon time, I approximated it checking lunarAgePercent:

```
2023-02-20T00:20:00.000Z -> 0.9999708226112602
2023-02-20T00:21:00.000Z -> 0.9999943387321082
2023-02-20T00:22:00.000Z -> 0.00001785483715366354
2023-02-20T00:23:00.000Z -> 0.00004137094219913706
```

So it says, that February new moon is Feb 20, 0:22UTC, but public data and `pyephem` library say that it will be 7:06UTC

**Comment by jasonsturges** [comment]
There are primary and intermediary phases.

The idea of an event is difficult to encapsulate here - it would be a fractional moment in time, essentially never shown.

Original intent of this package was weather station graphics implementation, giving a user indication of the current phase.  Essentially, rounding to the nearest phase.

This is discussed in other tickets.

**Comment by dannylin108** [comment]
I mean not a new moon phase (3.54 days), I mean exact new moon moment. 

So according to your library, in Feb 20, 2023, `lunarAgePercentage` from 0.999 becomes 0.001 around 0:22UTC, which means that new moon moment occurs at this time. Which is wrong.
