### ISSUE TITLE
trading view has different moon phases than this

### ISSUE THREAD

**Issue by benzmuircroft** [jasonsturges/lunarphase-js#29]
On trading view https://www.tradingview.com/chart/?symbol=BITSTAMP%3ABTCUSD

they have a free indicator that you can place over charts. It shows full and new moons. Why are their phases completely different from lunarphase-js in every case? Are they wrong?

**Comment by jasonsturges** [comment]
I have no idea what Trading View does, or how moon phases correlate to the trade of bitcoin.

Looks like there's more than one indicator, with questionable implementation.

Original intent of this package was weather station graphics implementation, giving a user indication of the current phase.  

There are primary and intermediate phases, as well as different lunation intercalation - some alternate 29 and 30 days, whereas this ~29.5 average developed by Stephen Schmitt provides accuracy for the next 31,000 years at which point this calculation will be 1-day behind.

![image](https://user-images.githubusercontent.com/1213591/220000988-c36b6097-8605-42a7-a97d-939b7d67fe15.png)

There have been many requests from astrology to now market trading, and I intend to complete a moon options system where you can specify a configuration to meet your needs:

```ts
export const defaultMoonOptionsFactory = (): MoonOptions => ({
  cycleStart: CycleStart.EVENT,
  hemisphere: Hemisphere.NORTHERN,
});
```

This is unfortunately low on my priority scale with many competing endeavors.

But I imagine I'll get to it sometime this year.
